apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  app: mongodb
type: Opaque
data:
  MONGODB_DATABASE: cXVpemFwcAo=
  MONGODB_USERNAME: cXVpemFwcAo=
  MONGODB_PASSWORD: VmVyeVN0cm9uZ1Bhc3N3b3JkMTIzCg==

